network:
  # PVE external IP address
  external_ip: '12.34.56.78'
  # PVE internal network
  internal_network: '10.0.0.0/24'
  # LAN interface with CTs and VMs
  internal_interface: vmbr0
  # WAN interface
  external_interface: enp1s0

# Ports are described as "External IP" <-> "Internal IP"
# All ports on external IP will be opened automatically
rules:
  10.0.0.101:
    tcp:
      22101: 22
    udp:
      30300: 30300

  10.0.0.102:
    tcp:
      22102: 22
      5432: 5432